engines:
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
ratings:
  paths:
  - "src/**/*.js"
exclude_paths:
- "**.spec.js"
- "__mock__/"
- "demo/"
- "docs/"
- "tools/"
- "webpack/"